"""initial_schema

Revision ID: 68239facb43f
Revises: 
Create Date: 2026-03-18 08:13:48.867233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68239facb43f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'VIEWER', name='userrole', create_constraint=True), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PLANNING', 'BRAINSTORMING', 'RESEARCHING', 'ARCHITECTING', 'DESIGNING', 'IMPLEMENTING', 'REVIEWING', 'TESTING', 'DEBUGGING', 'DOCUMENTING', 'DEPLOYING', 'DELIVERING', 'COMPLETED', 'FAILED', 'PAUSED', 'CANCELLED', name='projectstatus', create_constraint=True), nullable=False),
    sa.Column('project_type', sa.Enum('GREENFIELD', 'INFLIGHT', 'BROWNFIELD', 'IMPROVE', name='projecttype', create_constraint=True), nullable=False),
    sa.Column('prd_content', sa.Text(), nullable=False),
    sa.Column('prd_format', sa.Enum('markdown', 'json', 'yaml', name='prdformat', create_constraint=True), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('tech_stack_config_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('repository_path', sa.String(length=1024), nullable=False),
    sa.Column('repository_url', sa.String(length=1024), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('agent_type', sa.Enum('ORCHESTRATOR', 'PLANNER', 'RESEARCHER', 'ARCHITECT', 'DESIGNER', 'FRONTEND_DEV', 'BACKEND_DEV', 'MIDDLEWARE_DEV', 'INFRA_ENGINEER', 'SECURITY_AUDITOR', 'CODE_REVIEWER', 'TESTER', 'DEBUGGER', 'DOC_WRITER', 'BRAINSTORM_FACILITATOR', 'TECH_STACK_ADVISOR', 'TEMPLATE_CURATOR', 'DEPLOYER', 'COLLABORATION_MANAGER', 'MOBILE_DEV', 'PERFORMANCE_TESTER', 'ACCESSIBILITY_AUDITOR', 'GITHUB_INTEGRATOR', 'SKILL_MANAGER', 'HOOK_MANAGER', 'TOOL_BUILDER', 'INTEGRATION_ADAPTER', 'I18N_SPECIALIST', 'API_DESIGNER', 'PROJECT_MANAGER', name='agenttype', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'INITIALIZING', 'RUNNING', 'WAITING', 'COMPLETED', 'FAILED', 'TERMINATED', name='agentstatus', create_constraint=True), nullable=False),
    sa.Column('llm_provider', sa.String(length=128), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('worktree_path', sa.String(length=1024), nullable=True),
    sa.Column('cli_agent_type', sa.String(length=128), nullable=True),
    sa.Column('system_prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipelines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='pipelinestatus', create_constraint=True), nullable=False),
    sa.Column('current_phase', sa.String(length=255), nullable=False),
    sa.Column('graph_definition', sa.JSON(), nullable=True),
    sa.Column('checkpoint_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('test_suite', sa.String(length=512), nullable=False),
    sa.Column('test_name', sa.String(length=512), nullable=False),
    sa.Column('test_file', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'SKIPPED', 'ERROR', name='teststatus', create_constraint=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('framework', sa.String(length=128), nullable=False),
    sa.Column('coverage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('phase_name', sa.String(length=255), nullable=False),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.Column('git_commit_sha', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Enum('CREATE', 'MODIFY', 'DELETE', name='artifactoperation', create_constraint=True), nullable=False),
    sa.Column('git_commit_sha', sa.String(length=64), nullable=False),
    sa.Column('git_branch', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('AGENT_STARTED', 'AGENT_COMPLETED', 'AGENT_FAILED', 'TASK_CREATED', 'TASK_COMPLETED', 'TASK_FAILED', 'PHASE_STARTED', 'PHASE_COMPLETED', 'PIPELINE_STARTED', 'PIPELINE_COMPLETED', 'BRAINSTORM_MESSAGE', 'BRAINSTORM_FINALIZED', 'DEPLOYMENT_STARTED', 'DEPLOYMENT_COMPLETED', 'DEPLOYMENT_FAILED', 'DEPLOYMENT_ROLLED_BACK', 'COLLABORATION_JOINED', 'COLLABORATION_LEFT', 'COLLABORATION_CONFLICT', 'COLLABORATION_RESOLVED', 'GITHUB_PUSH', 'GITHUB_PR_CREATED', 'GITHUB_PR_MERGED', 'GITHUB_ISSUE_CREATED', 'GITHUB_ISSUE_CLOSED', 'GITHUB_WEBHOOK_RECEIVED', 'SKILL_CREATED', 'SKILL_EXECUTED', 'HOOK_TRIGGERED', 'HOOK_COMPLETED', 'TOOL_REGISTERED', 'TOOL_INVOKED', 'PERFORMANCE_REPORT_GENERATED', 'ACCESSIBILITY_REPORT_GENERATED', name='eventtype', create_constraint=True), nullable=False),
    sa.Column('source_agent_id', sa.Uuid(), nullable=True),
    sa.Column('target_agent_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=128), nullable=False),
    sa.Column('experiment_number', sa.Integer(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('git_branch', sa.String(length=255), nullable=False),
    sa.Column('git_commit_sha', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_before', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('metric_after', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('metric_delta', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('regression_checks', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('KEEP', 'DISCARD', 'CRASH', 'TIMEOUT', 'REGRESSION', name='experimentstatus', create_constraint=True), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('diff_lines_added', sa.Integer(), nullable=False),
    sa.Column('diff_lines_removed', sa.Integer(), nullable=False),
    sa.Column('complexity_delta', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('token_cost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_phases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phase_type', sa.Enum('BRAINSTORMING', 'TECH_STACK_SELECTION', 'TEMPLATE_SELECTION', 'PLANNING', 'RESEARCH', 'ARCHITECTURE', 'DESIGN', 'IMPLEMENTATION', 'REVIEW', 'TESTING', 'DEBUG_FIX', 'DOCUMENTATION', 'DEPLOYMENT', 'DELIVERY', name='phasetype', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WAITING_APPROVAL', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='phasestatus', create_constraint=True), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('comment_type', sa.Enum('BUG', 'STYLE', 'PERFORMANCE', 'SECURITY', 'ARCHITECTURE', 'SUGGESTION', name='commenttype', create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity', create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='commentstatus', create_constraint=True), nullable=False),
    sa.Column('resolved_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('scanner', sa.String(length=128), nullable=False),
    sa.Column('finding_type', sa.Enum('VULNERABILITY', 'SECRET', 'LICENSE_VIOLATION', 'CODE_SMELL', 'DEPENDENCY_RISK', 'CONFIG_ISSUE', name='findingtype', create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity', create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('cwe_id', sa.String(length=64), nullable=True),
    sa.Column('cve_id', sa.String(length=64), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'FIXED', 'ACCEPTED_RISK', 'FALSE_POSITIVE', name='findingstatus', create_constraint=True), nullable=False),
    sa.Column('fixed_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('fixed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixed_by_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('phase_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BLOCKED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus', create_constraint=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('assigned_agent_type', sa.String(length=255), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('input_context', sa.JSON(), nullable=True),
    sa.Column('output_artifacts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phase_id'], ['pipeline_phases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('llm_provider', sa.String(length=128), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'TIMEOUT', 'RATE_LIMITED', 'CANCELLED', name='executionstatus', create_constraint=True), nullable=False),
    sa.Column('input_messages', sa.JSON(), nullable=True),
    sa.Column('output_messages', sa.JSON(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_executions')
    op.drop_table('tasks')
    op.drop_table('security_findings')
    op.drop_table('review_comments')
    op.drop_table('pipeline_phases')
    op.drop_table('experiment_logs')
    op.drop_table('events')
    op.drop_table('code_artifacts')
    op.drop_table('checkpoints')
    op.drop_table('test_results')
    op.drop_table('pipelines')
    op.drop_table('agents')
    op.drop_table('projects')
    op.drop_table('audit_logs')
    op.drop_table('api_keys')
    op.drop_table('users')
    # ### end Alembic commands ###
